### ISSUE TITLE
Error with nuxt 3.0.0-rc.9

### ISSUE THREAD

**Issue by andrewspy** [huang-julien/nuxt-runtime-compiler#16]
It seems the module is no longer working with the latest nuxt 3.0.0-rc.9, as it is expecting `.output\server\node_modules\vue\server-renderer\index.js`, but the build generate `.output\server\node_modules\vue\server-renderer\index.mjs` instead.

Below is the error in `nuxt preview` after `nuxt build`:

```
[nuxt] [request error] [unhandled] [500] Cannot find module 'C:\nuxt-app\.output\server\node_modules\vue\server-renderer\index.js'
  at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
  at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
  at resolveExports (node:internal/modules/cjs/loader:482:14)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)      
  at Function.Module._load (node:internal/modules/cjs/loader:778:27)
  at Module.require (node:internal/modules/cjs/loader:1005:19)
  at require (node:internal/modules/cjs/helpers:102:18)
  at eval (eval at ssrCompile (C:\nuxt-app\.output\server\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:109:38), <anonymous>:4:119)     
  at ssrCompile (C:\nuxt-app\.output\server\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:109:63)
```

**Comment by huang-julien** [comment]
I just reproduced the issue on the playground, it might be related to https://github.com/unjs/nitro/issues/456, https://github.com/nuxt/framework/issues/7105 .  i'm not sure why nitro retrieve index.js instead of index.mjs

**Comment by huang-julien** [comment]
Should be good now, try to update the module to 1.0.10.
